backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: 'assets/uploads'
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: docs
    label: Docs
    label_singular: 'Doc'
    folder: 'docs'
    path: '{{title}}/{{id}}'
    slug: '{{id}}'
    create: true
    nested: { depth: 100 } # accepts an optional summary template
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - {
          label: "Posisi",
          name: "sidebar_position",
          widget: "string",
          required: false,
        }
      - { label: "Keterangan", name: "body", widget: "markdown" }
    allow_nesting: true
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }